all:
	latexmk main.tex -pdflatex

clean:
	rm -rf *.aux
	rm -rf *.log
	rm -rf *.out
	rm -rf *.pdf
	rm -rf *.pdfsync
	rm -rf *.gz
	rm -rf *.fdb_latexmk
	rm -rf *.fls
	rm -rf *.bbl
	rm -rf *.bcf
	rm -rf *.blg
	rm -rf *.xml
	rm -rf *.lof
	rm -rf *.lot
	rm -rf *.toc
	rm -rf *.xdv
